quantum-elixir/quantum-core

lib/quantum.ex, mix.exs, test/quantum_test.exs
Re: #1 
My use case for this is that anonymous functions in the config file are incompatible with my deployment procedure, and, unless I'm wrong, anyone else using exrm.
=> Add ability to schedule jobs at runtime and ability to view jobs

README.md, lib/quantum/executor.ex, lib/quantum/normalizer.ex, test/executor_test.exs, test/normalizer_test.exs
@c-rack thanks for quantum first of all :)
I've got some troubles using quantum with exrm.
First I need to generate some configs like this:
```
$ mix conform.new
$ mix conform.configure
```
and after
```
$ mix conform.effective
```
it fails. Looks like it can't convert quantum's config into his own of release. I've tried many variants and decided to use simple form of configuration, just like in cron:
```
* * * * * MyApp.MyModule.my_method
```
Configuration looks like:
```
config :quantum, cron: [
"* * * * * MyApp.MyModule.my_method"
]
```
Hope this will be useful for others.
=> Some adaption for conform/exrm

mix.exs
See this commit for further details:
https://github.com/hexpm/hex/commit/3dd315b2567cdb94f37747bf8dd8a63eda1bca0b
=> Solution: rename "contributors" to "maintainers" in mix.exs

README.md
Hi, I'm considering using Quantum for a project and was trying some readme things out in my shell and ran into a couple of weird things in the readme.
I was playing around with the runtime named jobs (easiest to get started with in an interactive shell), and one part says:
> Find job:
```elixir
Quantum.delete_job(:ok_job)
Quantum.delete_job(:news_letter)
```
Even though delete_job does return a job, I'm pretty sure this is supposed to be the function `find_job`.
Another problem is with the shown reponse. It does not return a tuple with the job name but just the job. I noticed the same issue with the `delete_job` function. I "fixed" this by updating the readme, I'm not sure if this is the way to go or if you'd rather have the functions return a tuple as the readme says now?
=> Problem: Incorrect function and response types in readme

lib/quantum/normalizer.ex, test/normalizer_test.exs
See https://github.com/c-rack/quantum-elixir/issues/43
Currently quantum-elixir does not support argument passing for unnamed jobs.  This PR adds support for arguments passed within tuples.
I would like to also support arguments within string inputs, yet have not quite figured out a clean way of doing that.  In the meantime I added an additional test for the current string behavior.
Review most welcome! I am not sure if this was the cleanest way of solving the issue.
=> Solution: unnamed job tuples cannot take args

lib/quantum.ex, test/quantum_test.exs
See #49 
Enable job names to be other types different to atoms. Any type that can be compared with === can be used as a job name.
Tests have been changed to use strings, atoms and charlists as job names.
=> Solution: job names can be other types different to atoms

.travis.yml, lib/quantum.ex, mix.exs, test/quantum_test.exs
See #82 
Use the `Task.Supervisor.async_nolink` introduced in Elixir 1.2.0 to spawn children jobs. This will avoid the crashing of the Quantum GenServer.
=> Solution: do not crash Quantum GenServer when child job process crashes

README.md, lib/quantum.ex, lib/quantum/executor.ex, lib/quantum/job.ex, mix.exs, test/executor_test.exs
This is by no means a finalized pull request, just a draft regarding #88 since you showed interest in it. The change adds optional per-job timezone support and is therefore backwards compatible -- current `Quantum` users should see no change in behavior.
A couple obvious things:
* `README.md` needs to be improved to demonstrate the new timezone features
* Test suite for a timezone other than default (UTC) should be written
* `w` field in `Executor` state is now obsolete/unused and should be removed, as weekday is calculated by `Timex` now
However before I write those things, I just wanted to get your feedback on the design of this feature; code quality, adherence to standards, and a second set of eyes to see if I missed something. The big differences that might be controversial are:
* …
=> Solution: Adding optional per-job timezone support.

mix.exs
Timex has been updated to avoid compilation warnings on v1.3, so it'd be nice for Quantum to use their v2.2.x
=> Update Timex to avoid Elixir v1.3 warnings

lib/quantum/executor.ex, mix.exs
Currently, Quantum relies on an older version of Timex.
This PR upgrades the Timex dependency to the latest 3.0. The `Timex.DateTime.from` call, which has been deprecated, is replaced with the equivalent `Timex.to_datetime`.
=> Problem: Quantum incompatible with Timex 3.0

lib/quantum/executor.ex
This Pull Request removes a compiler warning
```
warning: unused alias DateTime
```
=> Remove unused alias DateTime

README.md
Solution: remove license badge
See https://github.com/blog/2252-license-now-displayed-on-repository-overview
=> Problem: no need for license badge anymore

lib/quantum/executor.ex, lib/quantum/timer.ex, test/executor_test.exs, test/timer_test.exs
I took a shot at issue #108 . I came a solution that so far has been working for me, but this might need more testing. 
I also adapted the tests accordingly.
In case you have comments or suggestions on how to solve this in a better way, I'm open on improving the PR.
=> Solution: Timezone as string not working in config

lib/quantum/executor.ex, lib/quantum/timer.ex, mix.exs, test/executor_test.exs
Depending on a "local" timezone global variable is a bad idea. See more here: http://www.creativedeletion.com/2015/08/07/why-not-to-use-server-local-time.html
=> Don't allow "local" timezone. Replace Timex w. Calendar.

lib/quantum.ex
To run quantum as a global process with the current implement, I have to start quantum manually so I can deal with the crash in `start_link` for `already_started` process.
Solution: It should really be handled directly in quantum `start_link`, so all we need is the `global?` config to run quantum as a global process!
(slowly correcting the things I added)
=> Problem: global cannot be used directly

README.md, lib/quantum.ex, test/quantum_test.exs
We have several hundred background jobs and their number were increasing each day until we hit GenServer time out. This allows ability to specify `timeout` as part of quantum config. What do you think?
Something like below causes timeout on my system (which has relatively high load) for eg:
```
1..10_000 |> Enum.map(fn x -> Quantum.add_job("#{x}",  %Quantum.Job{schedule: "* */5 * * *", task: fn -> :ok end}) end)
```
=> add ability to specify genserver timeout

README.md
This PR solves issue #140 
The local timezone option has been removed. Update documentation to that effect. See PR [#122](https://github.com/c-rack/quantum-elixir/pull/122)
I did not include a note that the `local` option has been removed, I just removed references to it. If you'd prefer I add a note about the removal of the `local` option I'm happy to do that too.
=> Solution: Update README for removal of local timezone option

CHANGELOG.md, README.md, lib/quantum.ex, lib/quantum/application.ex, lib/quantum/executor.ex, lib/quantum/timer.ex, test/executor_test.exs, test/quantum_test.exs, test/timer_test.exs, test/timezone_test.exs
Implementation of #105
Implements Second Granularity.
Second specific Cron Expressions can be provided by specifying the `e` option of the `Crontab.CronExpression` Sigil.
* `~e[*/5]e` - Run Every 5 Seconds
* `~e[*/10 * */2]e` - Run Every 10 Seconds in every even hour
This PR is based on #144. After the merge of it, I'll rebase onto master again. Do not merge yet.
* Jobs without second granularity always run at second `0`.
* The notation `@every N seconds` is not needed with the sigil to specify cron expressions.
=> #105 Support Second Granularity

lib/quantum/config.ex, test/config_test.exs
The suggested migrated configuration tricked me into using "crons", which does nothing actually :)
=> Replace 'crons' with 'cron' in configuration example.

README.md
Just a tiny cosmetic fix in the README.
=> Use same style everywhere in README.md examples.

mix.exs
Starting an OTP release with quantum 1.9 fails (using distillery), and gives me a warning that crontab was not included in the release. The released application fails to start, given the crontab dependency is missing.
After adding it to the applications list and releasing, the warning is no longer present, and the application can start. I verified that the one job I have is indeed being run.
=> Add crontab to applications

lib/quantum/normalizer.ex, test/normalizer_test.exs
Fix for #160 
The described issue happens because a struct like `%Quantum.Job{schedule: "* * * * *", task: fn -> Logger.info("tick") end}` was not properly normalized.
Expected Normalizer Output:
```
%Quantum.Job{name: :something, pid: nil, state: :active, timezone: :utc, args: [],
nodes: [:nonode@nohost], overlap: true, schedule: ~e[* * * * *],
task: fn -> Logger.info("tick") end}
```
Actual Output:
```
%Quantum.Job{name: :newsletter, pid: nil, state: :active, timezone: :utc, args: [],
nodes: [:nonode@nohost], overlap: true, schedule: "* * * * *",
task: fn -> Logger.info("tick") end}
```
(The difference it the not normalized schedule.)
The proposed solution normalizes all values except just the `nodes` and `name`.
=> Solution: Quantum.Job Structs are not correctly normalized

CHANGELOG.md, mix.exs
It would be nice to see some more information in the ExDoc documentation.
This PR adds the Changelog to ExDoc & Formats it in a way that works for ExDoc.
=> Solution: Changelog Missing in ExDoc

lib/quantum/job.ex
I had a scenario, where I shut down quantum in current node and transfer all jobs to other. When running the jobs from the other node, even though the PIDs are now global ones, :erlang.is_process_alive works only with local nodes.
Let me know if you think this might help others.
=> PID can be remote ID. Do not throw error when checking if alive process

README.md, lib/quantum.ex, lib/quantum/executor.ex, lib/quantum/job.ex, lib/quantum/normalizer.ex, lib/quantum/scheduler.ex, lib/quantum/supervisor.ex, pages/configuration.md, pages/runtime.md, test/executor_test.exs, test/normalizer_test.exs, test/quantum/job_test.exs, test/quantum_startup_test.exs, test/quantum_test.exs, test/timezone_test.exs
Implementation of #174 
This PR cleans up the config notations.
The `args` property of the `Quantum.Job` is now embedded in the `task`.
This is a huge BC break (although it is easy to fix). It can not be released until the other big BC breaks are done too. (for example #152)
This is not yet thoroughly tested.
=> Solution: Less Config Notations

lib/quantum/job.ex, lib/quantum/normalizer.ex, lib/quantum/run_strategy.ex, lib/quantum/run_strategy/all.ex, lib/quantum/run_strategy/random.ex, lib/quantum/runner.ex, lib/quantum/scheduler.ex, lib/quantum/supervisor.ex, test/quantum/normalizer_test.exs, test/quantum_test.exs
Implementation of #180 
I had another idea on how to solve the issue. It should be extendable very easy.
Instead of `job.nodes` there is `job.run_strategy` (Protocol: `Quantum.RunStrategy`).
There are currently two run strategies supported:
* `Quantum.RunStrategy.All` - Run job on all nodes of list / in cluster.
* `Quantum.RunStrategy.Random` - Run job on a random node of list / in cluster.
It is possible to write custom strategies by implementing the `Quantum.RunStrategy` protocol.
The code is currently not tested & documented. I just want to hear what you think about it.
If the idea is accepted, I'll have to do proper testing & documentation before merge.
Open Question:
* What can be configured via Mix Config? What Notation?
=> Solution: Implement Run Strategies

MIGRATE-V2.md, README.md, lib/quantum/normalizer.ex, pages/configuration.md, test/quantum/normalizer_test.exs
Also, I took the liberty of adding the implementation for keyword job notation mentioned in `MIGRATE-V2.md`.
=> Solution: Minor fixes for documetation

README.md
This includes a couple documentation updates for setting up Quantum with the changes from 2.0
Once a 2.0 beta version is released on hex the version listed in `deps` should be updated, but that is waiting on #184
=> Readme updates for version 2.0

CHANGELOG.md, README.md
* This doc page is generated from [MIGRATE-V2.md](https://github.com/c-rack/quantum-elixir/blob/ae534b/MIGRATE-V2.md)
=> Solution: Fix link migration-v2.html -> migrate-v2.html

lib/quantum/normalizer.ex, lib/quantum/scheduler.ex, test/quantum_test.exs
[Override default settings](https://github.com/c-rack/quantum-elixir/blob/b49e291/pages/configuration.md#override-default-settings) shows `default_schedule` can be set with a string, but it only works with a `Crontab.CronExpression` struct. This will normalize the schedule, allowing any of the schedule formats.
=> Allow all schedule formats for default schedule

lib/quantum/date_library/calendar.ex
Fixes the following warning, observed on Elixir 1.4.4 when using the Timex rather than the Calendar dependency:
```
warning: function Calendar.DateTime.shift_zone!/2 is undefined (module Calendar.DateTime is not available)
lib/quantum/date_library/calendar.ex:35
```
The module `Calendar` is defined by Elixir itself, so the conditional always evaluated to true. The hex package Calendar defines the module in use here, `Calendar.DateTime`.
=> Solution: Ensure Calendar.DateTime is compiled instead of Calendar

.travis.yml, test/quantum/normalizer_test.exs, test/quantum_test.exs
Fix #204 
I ran master `mix test` 50 times in a loop and managed to reproduce the CI build error 4 times.
With this fix, I ran the loop again for 100 times and saw no failures.
Some notes regarding the current code structure:
- Feels weird that the scheduler starts the supervisor, not the other way around
- Runner and Executor probably can use some module docs, their names are so confusing
- Data transformations (i.e. new job) could probably be separated from the code that belongs to running processes, hence you don't have to start up anything just to test configuration normalization
- More separation could be used to isolate spawning processes, where some don't require the others in order to work
=> Solution: simplify test setup and eliminate race condition

README.md, lib/quantum/application.ex, lib/quantum/date_library.ex, lib/quantum/date_library/calendar.ex, lib/quantum/date_library/timex.ex, mix.exs
* Use Elixir 1.4 Way to configure App Dependencies
* Change README to only mention the Elixir 1.4 Apps Configuration (1.3 is no longer supported)
* Mark many deps to not be in runtime
* Start Date Lib automatically (will hopefully prevent many user support requests)
=> Solution: Mix Application Cleanup

.travis.yml
Re-Run Travis Build as soon as it is fully released. (Build Zip on hex.pm seems missing at the moment.)
=> Solution: Test with Elixir 1.5

lib/quantum/runner.ex
This pull-request fixes #233. 
The function Quantum.Executor.execute_task_if_date_matches/2 requires the key :date to be present in the state parameter. So the date-variable has to be added before the initial execution of jobs in the function Quantum.Runner.init/1.
=> add date-key to state of Runner before running jobs

pages/configuration.md
Only `timezone` is used, not `default_timezone`.
=> Fix config option in docs

lib/quantum/normalizer.ex, test/quantum/normalizer_test.exs
Should fix #246 .
In fact, the cause is the same as in #214 : missing value (`:timezone`) in the `field` type.
But then I thought, maybe it's better to remove this type, since there is no easy way in Elixir to avoid duplication of a value list in the typespec.
=> Solution: Deleted Quantum.Normalizer.field type

lib/quantum/application.ex
hmmmmm, thanks first for the repo. 
but, after I upgraded to v2, I met the trouble when I using hot upgrade, just like:
```
iex(i_can_not_tell_you@i_can_not_tell_you)3> :release_handler.install_release('0.0.2', [{:update_paths, true}]) 
<0.7606.0>: reason: {'EXIT',{timeout,{sys,get_status,[<0.7606.0>]}}}
10:01:27.534 [error] release_handler: cannot find top supervisor for application :quantum
release_handler:install_release(Vsn="0.0.2" Opts=[{update_paths,true}]) failed, Reason={'EXIT',
{timeout,
{sys,
get_status,
[<0.7606.0>]}}}
```
just because here:
https://github.com/erlang/otp/blob/OTP-20.1/lib/sasl/src/release_handler_1.erl#L579-L607
Plz review. Thanks again.
=> add supervisor for hot upgrade

lib/quantum/job.ex, lib/quantum/normalizer.ex, lib/quantum/run_strategy/local.ex, pages/run-strategies.md, test/quantum/run_strategy_test.exs
Local run strategy is used for run task on local node,
```elixir
run_strategy: {Quantum.RunStrategy.All, [node()]}
```
<del>could get the same effect, but</del> Local strategy is more intuitive.
And I add the test case for run strategy. plz !
=> Solution: Add Local Run Strategy

lib/quantum/executor_supervisor.ex, lib/quantum/util.ex
This seems to generate confusion since we got the same report twice in 24 hours. I don't really like to have code like this in our codebase. What do you think @c-rack?
Is there a way to do this at compile time?
=> Solution: Omit gen_stage warning

lib/quantum/execution_broadcaster.ex, lib/quantum/executor.ex, lib/quantum/job_broadcaster.ex
Recently I read [article](https://medium.com/learn-elixir/speed-up-data-access-in-elixir-842617030514) about the `Access` module and ways of accessing `Map` values in Elixir. It turned out that accessing values by e.g. `job.name` is slower than pattern matching. 
I thought I could improve your great library with this small change. What do you think @c-rack?
I was also thinking about improving specifications and typing in affected files. Is it worth it?
=> Prefer pattern matching over key access

CHANGELOG.md
Diff for the 2.2.5 version is now correct. 
Closes #319.
=> Solution: Fixed diff for 2.2.5

README.md, lib/quantum.ex, lib/quantum/execution_broadcaster.ex, lib/quantum/executor.ex, lib/quantum/executor_supervisor.ex, lib/quantum/job_broadcaster.ex, lib/quantum/task_stages_supervisor.ex, test/quantum/execution_broadcaster_test.exs, test/quantum/executor_test.exs, test/quantum/job_broadcaster_test.exs
_See also #331_
With this new configuration_option `debug_logging: false` (defaults to `true`) you can mute the Quantum debug-messages (if you want to use the `debug`-level of Logger for your own stuff).
=> Solution: Make Debug Logging Configurable

CHANGELOG.md, lib/quantum.ex, lib/quantum/execution_broadcaster.ex, lib/quantum/job.ex, lib/quantum/job_broadcaster.ex, lib/quantum/storage/adapter.ex, lib/quantum/storage/noop.ex, lib/quantum/task_stages_supervisor.ex, pages/configuration.md, test/quantum/execution_broadcaster_test.exs, test/quantum/job_broadcaster_test.exs, test/support/capture_log_extend.ex, test/support/test_storage.ex
~~Based on #317, merge that PR first.~~
Partial Implementation of #240
This PR is currently only to track changes, do not merge until it is proven to be working with an actual storage implementation.
=> Solution: Storage Adapter

lib/quantum/task_registry.ex, test/quantum/task_registry_test.exs
Closes: #344 
This PR adds functions for querying task registry if specific task is running in the cluster or if any tasks are running.
I have a question about doctests. All documented functions with examples in `TaskRegistry` module have doctests disabled. I followed what is currently there and listed the two new functions in `except`. Shall I delete doctests for this module or do you want to have them enabled and listed all functions in except?
Thanks for your time reviewing the changes!
=> Solution: Add helpers for querying task registry

config/.credo.exs, lib/quantum.ex, lib/quantum/cluster_task_supervisor_registry.ex, lib/quantum/executor.ex, lib/quantum/executor_supervisor.ex, lib/quantum/run_strategy.ex, lib/quantum/run_strategy/all.ex, lib/quantum/run_strategy/local.ex, lib/quantum/run_strategy/random.ex, lib/quantum/supervisor.ex, test/quantum/cluster_task_supervisor_registry_test.exs
Merge #351 first
Fix for #312
It was quite hard to prevent BC breaks. I think it would be the time soon to think about cleaning up the code and think of a cleaner way to implement the run strategies while keeping #241 in mind.
=> Solution: Implement Safer Run Strategies

lib/quantum/run_strategy/random.ex, test/quantum/run_strategy_test.exs
=> Solution: Fix Run Strategy Random

lib/quantum/date_library/timex.ex
Fix for Test failure observed in #383
=> Solution: Properly handle InvalidDateTimeForTimezoneError for newest timex version

lib/quantum/job.ex
I noticed that the docs of `Quantum.Job.set_task/2` was the same as `Quantum.Job.set_schedule/2`. This is to fix that and to add some missing apostrophes.
=> Fix documentation of Quantum.Job.set_task/2

lib/quantum/scheduler.ex
Sorry not to bundle it together with #400 but I have just noticed it.
=> Fixes typo in scheduler docs

lib/quantum.ex, lib/quantum/job.ex, test/quantum/job_test.exs
This commit adds to ability to define a job in a config as being inactive when initialising. This can be useful when you want to define certain jobs that you want to set active in the app at runtime without the need to configure the whole job at runtime.
=> Solution: make state configurable when defining the config

config/config.exs, lib/quantum/date_library/core.ex, mix.exs, test/quantum/date_library_test.exs
As the title says. I'm just not sure what would be the best way to put tzdata into the deps, as really it's probably not even an optional dependency. It would just need to be available for :dev and :test.
=> Implement date library using elixir 1.8s core functionality

CHANGELOG.md, mix.exs
This version will not contain a `global` mode. One can be re-added as soon as there is a sound replacement.
=> Release v3.0.0-rc.1

pages/configuration.md
As requested in #438, This PR adds `QuantumStorageMnesia` as a option to `Quantum.Storage`.
=> Adds QuantumStorageMnesia as a Quantum.Storage alternative

lib/quantum/clock_broadcaster.ex
The PR fixes ClockBroadcaster catch-up events creation order discussed in #441
=> Fixes catch-up events creation in reverse order

lib/quantum/executor.ex, test/quantum/executor_test.exs
Right now, a value is not always returned, as exits, exceptions, and thrown values are not handled inside the task.
This ensures a value is always returned.
=> feat: Handles task failures by returning a value

lib/quantum.ex, lib/quantum/clock_broadcaster.ex, lib/quantum/execution_broadcaster.ex, lib/quantum/executor_supervisor.ex, lib/quantum/job_broadcaster.ex, lib/quantum/node_selector_broadcaster.ex, lib/quantum/normalizer.ex, lib/quantum/supervisor.ex, lib/quantum/task_registry.ex
Allows Implementation of #411
This allows new libraries that start quantum on its own terms. Even the central `Supervisor` can be overwritten to allow full control.
For better handling with restarts, implementations could also provide a default `storage` that provides ephemeral storage inside the cluster. This would keep the storage as long as not all nodes in the cluster are restarted at the same time.
=> Supervision Configuration for Cluster Managers

config/config.exs, lib/quantum/clock_broadcaster.ex, lib/quantum/execution_broadcaster.ex, lib/quantum/executor.ex, lib/quantum/job_broadcaster.ex, lib/quantum/supervisor.ex, lib/quantum/task_registry.ex, test/quantum/executor_test.exs, test/quantum/job_broadcaster_test.exs
Fixes #460 
I have replaced the uses of dynamic messages in debug logs with static messages with dynamic logger metadata.
=> Uses logger metadata

lib/quantum/normalizer.ex, pages/configuration.md, test/quantum/normalizer_test.exs, test/quantum_startup_test.exs
Currently job `state` cannot be set through config. This is useful if we wish to start with jobs deactivated and activate them on runtime.
=> Support setting job `state` in scheduler's config

lib/quantum/executor.ex, test/quantum/executor_test.exs
Thanks for the amazing work on this package! Super helpful.
I ran into two issues:
* In production, when a job was failing, I wasn't getting any errors logged
* Additionally, none of these failures were being reported to my error monitoring (sentry)
Here's what I found:
* The reason I was't getting any errors logged was because I have my log level set to `info`. I'd expect most deployments to use a non-info log level.
* An exception from a scheduled job shouldn't be a `debug` log but instead should use something like `error`.
* If you are using an exception logging system such as sentry, you need `crash_reason` to exist in your log metadata for the log message to be treated as an exception. Here's an [example implementation in broadway](https://github.com/dashbitco/broadway/blob/master/lib …
=> Log exception with crash_reason

lib/quantum/job_broadcaster.ex, lib/quantum/storage.ex, test/quantum/job_broadcaster_test.exs, test/support/test_storage.ex
Add an optional `update_job` callback in `Quantum.Storage`. If this is implemented then it will be called when a job gets updated, otherwise the previous behaviour (delete and then add the job) will be used.
Rationale: I have created a `postgres` storage and the jobs are linked to other tables through foreign keys. With the current implementation every time a job is updated it deletes the current job and adds it again. I want to be able to just update the properties that have changed and leave everything else untouched.
=> Optional `update_job` callback in `Quantum.Storage`

config/config.exs, lib/quantum/execution_broadcaster.ex, lib/quantum/executor.ex, test/quantum/executor_test.exs
Includes the following changes:
- Make all tests work again (#466) (had to include `:crash_reason` in logger metadata, and remove the custom `:crash_reason` from `log_exception`
- Fix a bug in `ExecutionBroadcaster` . In case of invalid timezone no `state` was returned and as a result the `GenServer` was crashing:
```
22:41:29.638 [error] Invalid Timezone "foobar" provided for job :test.
22:41:29.655 [error] GenServer Jobex.Scheduler.ExecutionBroadcaster terminating
** (FunctionClauseError) no function clause matching in Quantum.ExecutionBroadcaster.sort_state/1
(quantum) lib/quantum/execution_broadcaster.ex:299: Quantum.ExecutionBroadcaster.sort_state(:ok)
(quantum) lib/quantum/execution_broadcaster.ex:170: Quantum.ExecutionBroadcaster.handle_event/2
(quantum) …
```
=> Fix tests and resolve a bug in ExecutionBroadcaster

README.md, pages/supervision-tree.md
The `import` statement is not necessary as noted in this issue: https://github.com/quantum-elixir/quantum-core/issues/474
Tested locally with a little dummy project - when the `warn: false` option was removed it confirmed that the import statement was unused:
```
warning: unused import Supervisor.Spec
lib/acme/application.ex:9
```
=> Solution: Remove Supervisor.Spec references

lib/quantum/executor.ex, mix.exs, test/quantum/executor_test.exs
There doesn't seem to be a clear reason to not use the proper span function.
I figured I would do the legwork here.
=> feat: Use `:telemetry.span/3`

mix.exs
The patch try to make this library support telemetry v1.0. Currently, it
doesn't because it contraint between [0.4.3, 1.0.0). Fix by using `or`
constraint to support both version.
=> Fix telemetry not support v1.0

pages/supervision-tree.md
In documentation mentioned that quantum will create `YourApp.Scheduler.Task.Supervisor` but
the correct one is `YourApp.Scheduler.TaskSupervisor`.
=> Fix incorrect TaskSupervisor name in documentation

mix.exs
Very basic minor change to allow for a graceful upgrade path on minor versions. Thank you!
=> Allow 1.x.x upgrades for telemetry

lib/quantum.ex, test/quantum_startup_test.exs
Hello!
**Proposal**:
At Quantum startup, when detected that a `mfa` `task` is not a  valid function, ignore the `job` configuration and show a `warning` message.
closes #507
=> Solution: add a warning message and remove jobs with invalid tasks

lib/quantum/node_selector_broadcaster.ex
When the running_node? function fails, only a warning log is returned. However, since the process is not executed due to a connection error, shouldn't this warning be an error?
This PR changes this warning to error so that the connection failure and the process not running are properly notified.
=> Changes warn to error when the function `check_node?` fails

lib/quantum.ex, lib/quantum/date_library.ex, lib/quantum/execution_broadcaster.ex
`Logger.warn/2` has been deprecated in Elixir 1.15.
=> Fix calls to deprecated Logger.warn/2

lib/quantum.ex
We had a problem where Quantum could only schedule a job right after executing `mix clean`, but with every call to `mix` after that, our configured jobs were not scheduled, because `function_exported?/3` returned false, even though the function still existed, but apparently was not yet exported at the time the Quantum code executed. This PR fixes this by calling `Code.ensure_loaded?/1` before `function_exported?/3`, which actively tries to load the module before returning `true` if this was successful or `false` otherwise (e.g. if the module does not exist).
=> fix problem with non-exported function
