lib/quantum.ex
hours are normally represented in 24h format ;)
=> fix hour constraints

README.md
Just spent an hour trying to understand why my crons are not working ... till I read the source and found the obvious. Hope this note helps others :)
=> make note about UTC

.travis.yml, README.md, mix.exs
=> Solution: add Inch-CI configuration and badge

README.md, lib/quantum.ex, lib/quantum/job.ex, lib/quantum/normalizer.ex, test/normalizer_test.exs, test/quantum_test.exs
@c-rack Sorry for long delay, just got the ability to solve the issues.
=> Nodes configuration and updated README

README.md
and change order for inch-ci badge
=> Solution: add total downloads badge

mix.exs
Additionally, shorten the description a little bit.
=> Solution: update ex_doc and excoveralls dependencies

CHANGELOG.md, mix.exs
=> Solution: add Lucas Charles as new maintainer

mix.exs
It could help us to improve and keep the code quality.
=> Add credo coder linter.

lib/quantum/executor.ex, test/executor_test.exs
=> Solution: add test case and fix error in executor

README.md
=> Solution: add ToC

lib/quantum.ex, lib/quantum/application.ex, lib/quantum/job.ex, lib/quantum/normalizer.ex, lib/quantum/translator.ex
Solution: fix them
Most of them are "line too long" issues.
=> Problem: credo reports code readability issues

mix.exs
=> Problem: dependency "earmark" is outdated

README.md
Solution: add explanation
Related to issue #66
=> Problem: option `overlap` is not well documented

README.md, lib/quantum/job.ex
Solution: allow default values to be configured
Fixes #67
=> Problem: default values are not configurable

lib/quantum/normalizer.ex, test/normalizer_test.exs
Solution: add test case and add overlap option in normalize step
Fixes #71
=> Problem: overlap option is not set to jobs

README.md
Solution: fix example with a version that works
=> Problem: readme has incorrect example how to add named job

test/test_helper.exs
Here is the pull request to enable the test.
=> enable startup-test

lib/quantum/application.ex, lib/quantum/normalizer.ex
=> Problem: credo complains about too long lines

README.md, test/timezone_test.exs
Here are the improvements as promised.
=> Solution: Improve README and test suites for timezone features

lib/quantum.ex, lib/quantum/executor.ex
=> Problem: credo warns about code style issues

mix.exs
Solution: remove docs from the link section
=> Problem: hex.pm shows already a link to the docs

lib/quantum/executor.ex
Solution: replace them with an underscore
=> Problem: elixir warns about unused variables

test/executor_test.exs
Solution: Add tests around timezone configuration
I'm not super happy with this approach as it feels a bit messy and manual, but couldn't think of a cleaner way to test the configuration. I would be open to suggestions and changes, but this gets us back up to 100% coverage :)
=> Problem: Code coverage below 100%

README.md, mix.exs
Solution: remove duplication
Solution: remove PATCH version from `timex` dependency
=> Problem: duplicate examples in README

lib/quantum.ex
Solution: run quantum as a globally unique process in a cluster
Closes #102
=> Problem: same task could be generated multiple times in a cluster

README.md
Solution: mention it in README.md
=> Problem: forgot to mention new global process config in readme

lib/quantum.ex, mix.exs
also fixed an indentation in mix.exs
=> Problem: process name is unnecessarily resolved at runtime

README.md
=> Problem: RFC22 of C4 process is deprecated

lib/quantum.ex, lib/quantum/job.ex, mix.exs
Solution: combine all checks in a helper function
Additionally, update dependencies to latest versions.
=> Problem: checking if job shall be executed is inconsistent

README.md
Solution: delete readme referencing setting timezones with timex
=> Problem: timex references in readme

README.md
=> Problem: support for timezones other than utc or local not in readme

CHANGELOG.md, README.md, lib/quantum/application.ex, lib/quantum/config.ex, test/config_test.exs, test/quantum_startup_test.exs
=> #104 Umbrella Configuration

test/quantum_startup_test.exs
There was some Log Output in the Test Suite. This PR mutes it.
```
12:09:36.253 [warn]  Job 'test_job' not started due to duplicate job name
12:09:36.255 [info]  Application quantum exited: :stopped
```
=> Mute Test Output via Logger

CHANGELOG.md, README.md, mix.exs
Merge after #149 & #150 are merged.
=> Bump Version to v1.9.0

mix.exs, pages/Error Handling.md
This extra documentation is supposed to show a user of this library on how to build a supervision tree for all cron jobs.
Solves #158
=> Solution: Unclear how to build Error Handling for Jobs

lib/quantum.ex, lib/quantum/config.ex, lib/quantum/executor.ex, lib/quantum/timer.ex
Solution: refactor reported code parts
=> Problem: credo reports refactoring opportunities

mix.exs
Solution: update to latest 0.17.*
=> Problem: calendar dependency is outdated

pages/configuration.md
=> Solution: Uncertainty on use of config notations

README.md, lib/quantum.ex, lib/quantum/executor.ex, lib/quantum/job.ex, lib/quantum/normalizer.ex, lib/quantum/scheduler.ex, lib/quantum/supervisor.ex, lib/quantum/timer.ex, pages/configuration.md, pages/runtime.md, test/executor_test.exs, test/normalizer_test.exs, test/quantum/job_test.exs, test/quantum_startup_test.exs, test/quantum_test.exs, test/timer_test.exs, test/timezone_test.exs
Implementation of #172 
Depends on #178. Merge & Rebase First.
=> Solution: Clear Timezone Handling

README.md, lib/quantum.ex, lib/quantum/date_library.ex, lib/quantum/date_library/calendar.ex, lib/quantum/date_library/timex.ex, lib/quantum/executor.ex, lib/quantum/job.ex, lib/quantum/normalizer.ex, lib/quantum/scheduler.ex, lib/quantum/supervisor.ex, lib/quantum/timer.ex, mix.exs, pages/configuration.md, pages/date-library.md, pages/runtime.md, test/date_library_test.exs, test/executor_test.exs, test/normalizer_test.exs, test/quantum/job_test.exs, test/quantum_startup_test.exs, test/quantum_test.exs, test/timer_test.exs, test/timezone_test.exs
Implementation of #176 
This PR has now Breaking Changes. It has to be released with the other `v2` PR's.
This PR depends on #181. Merge & Rebase first.
=> Solution: Support both Calendar, Timex & possibly other date libraries

MIGRATE-V2.md, README.md, lib/quantum/job.ex, lib/quantum/normalizer.ex, lib/quantum/run_strategy.ex, lib/quantum/run_strategy/all.ex, lib/quantum/run_strategy/random.ex, lib/quantum/runner.ex, lib/quantum/scheduler.ex, lib/quantum/supervisor.ex, mix.exs, pages/configuration.md, pages/run-strategies.md, test/quantum/normalizer_test.exs
=> Solution: Config Normalization for Run Strategies

lib/quantum/supervisor.ex
If a user only wants to do runtime configuration.
=> Solution: Allow Missing Configuration

lib/quantum/runner.ex
Should fix #189 .
Please review.
=> Solution: check if task supervisor is running on the target node

lib/quantum/config.ex, test/config_test.exs
=> Solution: Fix Deprecated Config Message

README.md
=> Problem: timex was removed from list of apps

pages/configuration.md, pages/crontab-format.md
Solution to https://github.com/c-rack/quantum-elixir/issues/184#issuecomment-305942499
=> Solution: Documentation Improvements

lib/quantum/scheduler.ex
Partial Implementation from #196
=> Solution: Copy docs from Quantum.Scheduler to Implementation

lib/quantum/job.ex
=> Fix #210: Dialyzer warns when use Quantum.Scheduler

lib/quantum.ex, lib/quantum/executor.ex, lib/quantum/job.ex, lib/quantum/normalizer.ex, lib/quantum/runner.ex, lib/quantum/scheduler.ex, lib/quantum/supervisor.ex, mix.exs, pages/configuration.md, pages/run-strategies.md, pages/runtime.md, test/quantum/job_test.exs, test/quantum/quantum_test.exs, test/quantum/scheduler_test.exs, test/quantum_startup_test.exs
=> Solution: More Flexible Scheduler

dialyzer.ignore-warnings, lib/quantum/run_strategy.ex, mix.exs
Partial Implementation of #214
=> Solution: Mute Dialyzer Warnings for Protocol

lib/quantum/normalizer.ex, test/normalizer_test.exs
=> Solution: Normalize Timezone from Config

lib/quantum/normalizer.ex
=> Solution: Fix Quantum.Normalizer.field type

lib/quantum/scheduler.ex, test/quantum/scheduler_test.exs
=> Solution: Cleanup Scheduler Test

lib/quantum/normalizer.ex, test/normalizer_test.exs
=> Solution: Named Job in Runtime Name No nil

lib/quantum/normalizer.ex, test/quantum/normalizer_test.exs
Fix for #248 
This fix will also be merged into the `master` branch.
* `v2.0.1`
* `v2.1.0`
=> Solution: Fix Normalization of Timezone

CHANGELOG.md, README.md, mix.exs
=> Release v2.0.1

CHANGELOG.md, README.md, mix.exs
Sorry, I forgot to release the doc update. (Already in `2.0-dev` branch)
=> Release v2.0.2

lib/quantum/executor.ex, lib/quantum/runner.ex
=> Solution: Reboot Only Run on Start

CHANGELOG.md, lib/quantum/runner.ex
=> Solution: Fix Race Condition of reboot in Runner state

test/quantum/executor_test.exs, test/timezone_test.exs
I seem to have broken the tests with PR #258.
=> Solution: Fix Tests for Executor Fix

.travis.yml, dialyzer.ignore-warnings, lib/quantum.ex, lib/quantum/job.ex, lib/quantum/normalizer.ex
=> Solution: Fix Dialyzer Warnings

pages/configuration.md
Solution: add distillery and emphasize anonymous functions are not supported
=> Problem: distillery is not mentioned in list of package managers

.formatter.exs, lib/quantum.ex, lib/quantum/date_library.ex, lib/quantum/date_library/calendar.ex, lib/quantum/date_library/timex.ex, lib/quantum/execution_broadcaster.ex, lib/quantum/executor.ex, lib/quantum/executor_supervisor.ex, lib/quantum/job.ex, lib/quantum/job_bradcaster.ex, lib/quantum/normalizer.ex, lib/quantum/run_strategy.ex, lib/quantum/run_strategy/all.ex, lib/quantum/run_strategy/random.ex, lib/quantum/scheduler.ex, lib/quantum/supervisor.ex, lib/quantum/task_registry.ex, lib/quantum/util.ex, mix.exs, test/quantum/date_library_test.exs, test/quantum/execution_broadcaster_test.exs, test/quantum/executor_test.exs, test/quantum/job_broadcaster_test.exs, test/quantum/job_test.exs, test/quantum/normalizer_test.exs, test/quantum/scheduler_test.exs, test/quantum_startup_test.exs, test/support/test_consumer.ex
Solution: use Elixir's upcoming `mix format` to automatically re-format source
See https://hashrocket.com/blog/posts/format-your-elixir-code-now
=> Problem: source is not formatted properly

CHANGELOG.md, lib/quantum/execution_broadcaster.ex, test/quantum/execution_broadcaster_test.exs
=> Solution: Runtime Job start on first execution

lib/quantum.ex, lib/quantum/supervisor.ex, lib/quantum/task_stages_supervisor.ex
=> Solution: Fix running jobs in cluster

README.md, lib/quantum/execution_broadcaster.ex, lib/quantum/executor.ex, lib/quantum/job_bradcaster.ex, test/quantum/execution_broadcaster_test.exs, test/quantum/executor_test.exs, test/quantum/job_broadcaster_test.exs, test/quantum/scheduler_test.exs, test/quantum_startup_test.exs
=> Solution: Add better debugging capabilities

.travis.yml
=> Solution: Update CI Config to use Jobs

.formatter.exs, .travis.yml, lib/quantum.ex, lib/quantum/execution_broadcaster.ex, lib/quantum/executor.ex, lib/quantum/job.ex, lib/quantum/job_broadcaster.ex, lib/quantum/normalizer.ex, lib/quantum/scheduler.ex, lib/quantum/task_stages_supervisor.ex, test/quantum/executor_test.exs, test/quantum/scheduler_test.exs, test/quantum_startup_test.exs
=> Solution: Reformat Code

.travis.yml
=> Solution: Run Travis-CI with Elixir 1.6

lib/quantum/executor_supervisor.ex
=> Solution: Make quantum work again with gen_stage v0.12.2

mix.exs
=> Solution: Relax timex dependency requirements

lib/quantum/date_library.ex, lib/quantum/date_library/calendar.ex, lib/quantum/date_library/timex.ex, lib/quantum/execution_broadcaster.ex, test/quantum/date_library_test.exs, test/quantum/execution_broadcaster_test.exs
Fix for #321 
*I don't really like to test via the internal state of a GenServer. Has someone an idea how to test without it?*
=> Solution: Solve DST Bug

CHANGELOG.md, README.md, mix.exs
@c-rack I'm going to retire all older versions because of this bug. Is that ok for you?
=> Release v2.2.6

CHANGELOG.md, mix.exs
=> Release v2.2.7

lib/quantum/scheduler.ex
I using global mode to set the job and in multi-nodes env, and I'd like to get the `jobs`.
But if I get the jobs on one Elixir node which doesn't keep the global `MyApp.Scheduler.TaskStagesSupervisor` process, the error will happen:
```
1> MyApp.Scheduler.jobs
** (exit) exited in: GenServer.call(MyApp.Scheduler.JobBroadcaster, :jobs, 5000)
** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
(elixir) lib/gen_server.ex:821: GenServer.call/3
```
I scanned the code, and found,
1, the job broadcaster from here https://github.com/quantum-elixir/quantum-core/blob/master/lib/quantum/scheduler.ex#L66
2, the job broadcaster defined here …
=> Solution: solve job broadcaster process can not found in global mode

dialyzer.ignore-warnings, lib/quantum/job.ex, lib/quantum/normalizer.ex, lib/quantum/run_strategy/random.ex, test/quantum/cluster_task_supervisor_registry_test.exs, test/quantum/run_strategy_test.exs
* Make Tests Elixir 1.5 compatible
* Remove unsupported local timezone #73 
Merge #357 first!
=> Solution: Cleanup

.travis.yml, dialyzer.ignore-warnings, lib/quantum.ex, lib/quantum/clock_broadcaster.ex, lib/quantum/clock_broadcaster/event.ex, lib/quantum/clock_broadcaster/init_opts.ex, lib/quantum/clock_broadcaster/state.ex, lib/quantum/execution_broadcaster.ex, lib/quantum/execution_broadcaster/event.ex, lib/quantum/execution_broadcaster/init_opts.ex, lib/quantum/execution_broadcaster/state.ex, lib/quantum/executor.ex, lib/quantum/scheduler.ex, lib/quantum/supervisor.ex, mix.exs, test/quantum/clock_broadcaster_test.exs, test/quantum/execution_broadcaster_test.exs, test/quantum/executor_test.exs
Split Execution Broadcaster into two Broadcaster with more defined interfaces.
=> Solution: Introduce Clock Broadcaster to make Execution Broadcaster easier

CHANGELOG.md, dialyzer.ignore-warnings, lib/quantum.ex, lib/quantum/cluster_task_supervisor_registry.ex, lib/quantum/cluster_task_supervisor_registry/init_opts.ex, lib/quantum/cluster_task_supervisor_registry/start_opts.ex, lib/quantum/cluster_task_supervisor_registry/state.ex, lib/quantum/execution_broadcaster.ex, lib/quantum/execution_broadcaster/init_opts.ex, lib/quantum/execution_broadcaster/start_opts.ex, lib/quantum/execution_broadcaster/state.ex, lib/quantum/executor.ex, lib/quantum/executor/start_opts.ex, lib/quantum/executor_supervisor.ex, lib/quantum/executor_supervisor/init_opts.ex, lib/quantum/executor_supervisor/start_opts.ex, lib/quantum/job_broadcaster.ex, lib/quantum/job_broadcaster/init_opts.ex, lib/quantum/job_broadcaster/start_opts.ex, lib/quantum/job_broadcaster/state.ex, lib/quantum/scheduler.ex, lib/quantum/supervisor.ex, lib/quantum/task_registry.ex, lib/quantum/task_registry/init_opts.ex, lib/quantum/task_registry/start_opts.ex, lib/quantum/task_registry/state.ex, test/quantum/cluster_task_supervisor_registry_test.exs, test/quantum/execution_broadcaster_test.exs
Do not merge until testing is done together with @zacksiri
=> Solution: Fix Worker Config in Global & Cleanup Worker Options

lib/quantum/executor_supervisor.ex
=> Solution: Fix Executor Start Ops for GenStage v0.12

CHANGELOG.md, dialyzer.ignore-warnings, lib/quantum/execution_broadcaster.ex, lib/quantum/job_broadcaster.ex, test/quantum/execution_broadcaster_test.exs, test/quantum/executor_test.exs, test/quantum/job_broadcaster_test.exs, test/quantum/task_registry_test.exs, test/support/handoff_helper.ex, test/test_helper.exs
Partial Fix for #368
Also makes some tests less flaky.
=> Properly Implement & Test Swarm Problem Resolution

CHANGELOG.md, lib/quantum/cluster_task_supervisor_registry.ex, lib/quantum/cluster_task_supervisor_registry/init_opts.ex, lib/quantum/cluster_task_supervisor_registry/start_opts.ex, lib/quantum/cluster_task_supervisor_registry/state.ex, lib/quantum/supervisor.ex, test/quantum/cluster_task_supervisor_registry_test.exs
=> Solution: Faster startup for non-global

CHANGELOG.md, mix.exs
=> Release 2.3.4

lib/quantum/execution_broadcaster.ex, lib/quantum/job_broadcaster.ex, lib/quantum/task_registry.ex
Thanks for Quantum! Just a quick spelling correction.
=> correct spelling of "Incorporating"

pages/configuration.md
=> Update timezone support documentation

lib/quantum/execution_broadcaster.ex
=> Fix Reboot Schedule Jobs

lib/quantum/date_library.ex
=> Grammar: setup -> set up

lib/quantum/clock_broadcaster.ex, lib/quantum/clock_broadcaster/state.ex
=> Handle Clock Skew

CHANGELOG.md, lib/quantum/job_broadcaster.ex, test/quantum/job_broadcaster_test.exs
=> Solution: Properly override jobs with duplicate job name

CHANGELOG.md, lib/quantum/executor.ex, lib/quantum/job_broadcaster.ex, mix.exs, pages/telemetry.md, test/quantum/executor_test.exs, test/quantum/job_broadcaster_test.exs
=> Telemetry Fishish

lib/quantum/job_broadcaster.ex, test/quantum/job_broadcaster_test.exs
=> Fix Job Override

lib/quantum.ex, lib/quantum/job.ex, test/quantum/run_strategy_test.exs, test/quantum_startup_test.exs
=> Job Config Options

pages/runtime-configuration.md
=> Tiny Doc Fix

lib/quantum.ex, test/quantum_startup_test.exs
=> Fix Logs for invalid jobs

lib/quantum/normalizer.ex, test/quantum/normalizer_test.exs
=> Solution: Support options configuration for unnamed job
